FROM node:20-alpine
WORKDIR "/app"

RUN apk add --no-cache openssl

COPY ./package.json .
RUN npm i

RUN mkdir /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache
COPY . .

CMD ["sh", "-c", "npx prisma generate && npx prisma db push && npx prisma db seed && npm run dev"]